GET http://localhost:8080/hello/a

###

PUT http://localhost:8080/hello/tttem
Content-Type: application/json
{
  "DateOfBirth": 1991-12-15
}
###

curl -H 'Content-Type: application/json' -X PUT -d '{ "DateOfBirth": "1986-12-17" }' localhost:8080/hello/tttem | jq .

curl -X GET -v localhost:8080/hello/tttrm | jq .