apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo-pgsql
          image: 447446761662.dkr.ecr.us-east-2.amazonaws.com/echo-pgsql:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: echopgsql8080
          env:
            - name: DATABASE_HOST
              value: pgsql
            - name: DATABASE_PORT
              value: 5432
            - name: DATABASE_USER
              value: user
            - name: DATABASE_PASSWORD
              value: user
            - name: DATABASE_DBNAME
              value: user

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - image: postgres:10.6
          name: postgres
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              value: user
            - name: POSTGRES_USER
              value: user
            - name: PGDATA
              value: /var/lib/postgresql/data/widgetapi/
          ports:
            - containerPort: 5432
              name: postgres5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          awsElasticBlockStore:
            volumeID: vol-090ff07d80720c213 # must be created before deployment
            fsType: ext4

---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: pgsql